# Check the results of Featuretools

In [1]:
import numpy as np
import pandas as pd
import featuretools as ft
import time
%matplotlib inline

In [2]:
# load the feature matrix to check whether it was properly saved.

feature_matrix2 = pd.read_csv('../data/processed/feature_matrix_skip2_TF.csv')
feature_matrix2.sort_values(by = ['session_id','session_position'],inplace=True)
feature_matrix2.head().T

,0,10000,20000,30000,40000
event_id,0,1,2,3,4
session_id,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0_00006f66-33e5-4de7-a324-2d18e439fc1e
session_position,1,2,3,4,5
skip_1,False,False,False,False,False
skip_2,False,False,False,False,False
...,...,...,...,...,...
DIFF(tf.us_popularity_estimate) by session_id_skip_2_False,NaN,-0.071405,0.103248,-0.004938,0.00346
DIFF(tf.us_popularity_estimate) by session_id_skip_2_True,NaN,-0.042453,0.071113,0.068645,0.093392
DIFF(tf.valence) by session_id,NaN,0.184898,0.03671,0.275558,0.003501
DIFF(tf.valence) by session_id_skip_2_False,NaN,0.184898,0.03671,0.275558,0.003501
DIFF(tf.valence) by session_id_skip_2_True,NaN,-0.630121,-0.243083,-0.241902,-0.048903

In [3]:
#pd.set_option('display.max_rows', 1000)
pd.DataFrame(feature_matrix2.isna().sum())
#pd.set_option('display.max_rows', 60)

                                                        0
event_id                                                0
session_id                                              0
session_position                                        0
skip_1                                                  0
skip_2                                                  0
...                                                   ...
DIFF(tf.us_popularity_estimate) by session_id_s...  10001
DIFF(tf.us_popularity_estimate) by session_id_s...  10001
DIFF(tf.valence) by session_id                      10000
DIFF(tf.valence) by session_id_skip_2_False         10001
DIFF(tf.valence) by session_id_skip_2_True          10001

[739 rows x 1 columns]

In [4]:
# inspect the data of a session
a = feature_matrix2[feature_matrix2['session_id'] == '0_00006f66-33e5-4de7-a324-2d18e439fc1e']
# inspect whether the featuretools generated features considered the session and the order information. The answer appears yes.
a[['tf.speechiness','CUM_SUM(tf.speechiness) by session_id','session_id','CUM_SUM(tf.speechiness) by session_id_skip_2_False','session_id_skip_2_False','CUM_SUM(tf.speechiness) by session_id_skip_2_True','session_id_skip_2_True','session_position']]

,tf.speechiness,CUM_SUM(tf.speechiness) by session_id,session_id,CUM_SUM(tf.speechiness) by session_id_skip_2_False,session_id_skip_2_False,CUM_SUM(tf.speechiness) by session_id_skip_2_True,session_id_skip_2_True,session_position
0,0.069717,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.069717,NaN,1
10000,0.061158,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,847.522308,NaN,2
20000,0.045354,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1557.552254,NaN,3
30000,0.229936,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2241.373284,NaN,4
40000,0.240980,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2895.464496,NaN,5
50000,0.133586,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,3549.035841,NaN,6
60000,0.409848,1.190578,0_00006f66-33e5-4de7-a324-2d18e439fc1e,4292.574428,NaN,0.409848,0_00006f66-33e5-4de7-a324-2d18e439fc1e,7
70000,0.103687,1.294266,0_00006f66-33e5-4de7-a324-2d18e439fc1e,5077.962720,NaN,0.513535,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8
80000,0.049853,1.344119,0_00006f66-33e5-4de7-a324-2d18e439fc1e,5833.177385,NaN,0.563389,0_00006f66-33e5-4de7-a324-2d18e439fc1e,9
90000,0.154609,1.498729,0_00006f66-33e5-4de7-a324-2d18e439fc1e,6605.169306,NaN,0.717998,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10
100000,0.027932,1.526660,0_00006f66-33e5-4de7-a324-2d18e439fc1e,7340.522594,NaN,0.745930,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11
109181,0.414651,1.941311,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8023.947343,NaN,1.160581,0_00006f66-33e5-4de7-a324-2d18e439fc1e,12
117610,0.364139,2.305451,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8668.380266,NaN,1.524720,0_00006f66-33e5-4de7-a324-2d18e439fc1e,13
125393,0.256456,2.561906,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8502.134508,NaN,14
132629,0.125605,2.687512,0_00006f66-33e5-4de7-a324-2d18e439fc1e,9843.138501,NaN,1.650325,0_00006f66-33e5-4de7-a324-2d18e439fc1e,15
139406,0.424763,3.112275,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10356.556739,NaN,2.075088,0_00006f66-33e5-4de7-a324-2d18e439fc1e,16
145748,0.067412,3.179687,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10827.870482,NaN,2.142500,0_00006f66-33e5-4de7-a324-2d18e439fc1e,17
151751,0.140268,3.319955,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11282.839572,NaN,2.282769,0_00006f66-33e5-4de7-a324-2d18e439fc1e,18
157434,0.104258,3.424213,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11730.056003,NaN,2.387027,0_00006f66-33e5-4de7-a324-2d18e439fc1e,19
162814,0.419025,3.843238,0_00006f66-33e5-4de7-a324-2d18e439fc1e,12159.542654,NaN,2.806052,0_00006f66-33e5-4de7-a324-2d18e439fc1e,20

In [5]:
cols_skip_2_True = [col for col in feature_matrix2.columns if 'by session_id_skip_2_True' in col]
cols_skip_2_False = [col for col in feature_matrix2.columns if 'by session_id_skip_2_False' in col]

In [7]:
feature_matrix2.loc[feature_matrix2['session_id_skip_2_True'].isna(),cols_skip_2_True] = np.nan
feature_matrix2.loc[feature_matrix2['session_id_skip_2_False'].isna(),cols_skip_2_False] = np.nan
b = feature_matrix2[feature_matrix2['session_id'] == '0_00006f66-33e5-4de7-a324-2d18e439fc1e']
b[['tf.speechiness','CUM_SUM(tf.speechiness) by session_id','session_id','CUM_SUM(tf.speechiness) by session_id_skip_2_False','session_id_skip_2_False','CUM_SUM(tf.speechiness) by session_id_skip_2_True','session_id_skip_2_True','session_position']]

,tf.speechiness,CUM_SUM(tf.speechiness) by session_id,session_id,CUM_SUM(tf.speechiness) by session_id_skip_2_False,session_id_skip_2_False,CUM_SUM(tf.speechiness) by session_id_skip_2_True,session_id_skip_2_True,session_position
0,0.069717,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,1
10000,0.061158,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2
20000,0.045354,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,3
30000,0.229936,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,4
40000,0.240980,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,5
50000,0.133586,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,6
60000,0.409848,1.190578,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,0.409848,0_00006f66-33e5-4de7-a324-2d18e439fc1e,7
70000,0.103687,1.294266,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,0.513535,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8
80000,0.049853,1.344119,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,0.563389,0_00006f66-33e5-4de7-a324-2d18e439fc1e,9
90000,0.154609,1.498729,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,0.717998,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10
100000,0.027932,1.526660,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,0.745930,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11
109181,0.414651,1.941311,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,1.160581,0_00006f66-33e5-4de7-a324-2d18e439fc1e,12
117610,0.364139,2.305451,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,1.524720,0_00006f66-33e5-4de7-a324-2d18e439fc1e,13
125393,0.256456,2.561906,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,14
132629,0.125605,2.687512,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,1.650325,0_00006f66-33e5-4de7-a324-2d18e439fc1e,15
139406,0.424763,3.112275,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2.075088,0_00006f66-33e5-4de7-a324-2d18e439fc1e,16
145748,0.067412,3.179687,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2.142500,0_00006f66-33e5-4de7-a324-2d18e439fc1e,17
151751,0.140268,3.319955,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2.282769,0_00006f66-33e5-4de7-a324-2d18e439fc1e,18
157434,0.104258,3.424213,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2.387027,0_00006f66-33e5-4de7-a324-2d18e439fc1e,19
162814,0.419025,3.843238,0_00006f66-33e5-4de7-a324-2d18e439fc1e,NaN,NaN,2.806052,0_00006f66-33e5-4de7-a324-2d18e439fc1e,20

In [9]:
# shift the rows down by 1 within each session because it reflects the history (no_skip) up to the previous row
# without shifting, the information of no_skip will leak into the features!!
start_time = time.time()
feature_matrix2[cols_skip_2_True+cols_skip_2_False] = feature_matrix2.groupby(['session_id'])[cols_skip_2_True+cols_skip_2_False].shift(periods=1, axis=0, fill_value=0)
print('***It takes ',(time.time() - start_time)/60, ' mins.***')

***It takes  2.6390278895696  mins.***

In [10]:
start_time = time.time()

feature_matrix2 = feature_matrix2.groupby(['session_id'], sort = False).apply(lambda x: x.ffill())

#feature_matrix2.groupby(['session_id']).fillna(method='ffill', axis = 0, inplace=True)
print('***It takes ',(time.time() - start_time)/60, ' mins.***')

/var/folders/fw/slnm06yn15lgwlcg_7jpt3t00000gn/T/ipykernel_53822/1174794535.py:3: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  feature_matrix2 = feature_matrix2.groupby(['session_id'], sort = False).apply(lambda x: x.ffill())

***It takes  0.2248967965443929  mins.***

In [12]:
# check the data again after shifting the rows
b = feature_matrix2[feature_matrix2['session_id'] == '0_00006f66-33e5-4de7-a324-2d18e439fc1e']
# inspect whether the featuretools generated features considered the session and the order information. The answer appears yes.
b[['tf.speechiness','CUM_SUM(tf.speechiness) by session_id','session_id','CUM_SUM(tf.speechiness) by session_id_skip_2_False','session_id_skip_2_False','CUM_SUM(tf.speechiness) by session_id_skip_2_True','session_id_skip_2_True','session_position']]

,tf.speechiness,CUM_SUM(tf.speechiness) by session_id,session_id,CUM_SUM(tf.speechiness) by session_id_skip_2_False,session_id_skip_2_False,CUM_SUM(tf.speechiness) by session_id_skip_2_True,session_id_skip_2_True,session_position
0,0.069717,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,1
10000,0.061158,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.069717,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,2
20000,0.045354,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.130874,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,3
30000,0.229936,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.176229,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,4
40000,0.240980,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.406164,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,5
50000,0.133586,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.647144,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,NaN,6
60000,0.409848,1.190578,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.000000,0_00006f66-33e5-4de7-a324-2d18e439fc1e,7
70000,0.103687,1.294266,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.409848,0_00006f66-33e5-4de7-a324-2d18e439fc1e,8
80000,0.049853,1.344119,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.513535,0_00006f66-33e5-4de7-a324-2d18e439fc1e,9
90000,0.154609,1.498729,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.563389,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10
100000,0.027932,1.526660,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.717998,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11
109181,0.414651,1.941311,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.745930,0_00006f66-33e5-4de7-a324-2d18e439fc1e,12
117610,0.364139,2.305451,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.160581,0_00006f66-33e5-4de7-a324-2d18e439fc1e,13
125393,0.256456,2.561906,0_00006f66-33e5-4de7-a324-2d18e439fc1e,0.780730,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.524720,0_00006f66-33e5-4de7-a324-2d18e439fc1e,14
132629,0.125605,2.687512,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.524720,0_00006f66-33e5-4de7-a324-2d18e439fc1e,15
139406,0.424763,3.112275,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.650325,0_00006f66-33e5-4de7-a324-2d18e439fc1e,16
145748,0.067412,3.179687,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2.075088,0_00006f66-33e5-4de7-a324-2d18e439fc1e,17
151751,0.140268,3.319955,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2.142500,0_00006f66-33e5-4de7-a324-2d18e439fc1e,18
157434,0.104258,3.424213,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2.282769,0_00006f66-33e5-4de7-a324-2d18e439fc1e,19
162814,0.419025,3.843238,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1.037186,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2.387027,0_00006f66-33e5-4de7-a324-2d18e439fc1e,20

In [13]:
feature_matrix2.to_csv('../data/processed/feature_matrix_skip2_TF_processed.csv')

# Scale standardization & training/testing data split will be performed at the model fitting stage.